### ISSUE TITLE
ltsport.com/apptmng/Create 檢查一下

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#1]

**Comment by tacoring** [comment]
這問題之前好像有提過, 
我已經把整包Appt folder拷貝過來, 但是怎樣就是不能顯示. 

是不是就改成電話預約之類的.

**Comment by kevin-doselection** [comment]
這個功能要登入才會轉過去，你看能不能redirect到dashboard

**Comment by tacoring** [comment]
再dashboard裡頭就有appointment選項. 點進去是一片空白... :(

**Comment by kevin-doselection** [comment]
有錯誤error嗎？在手機版

**Comment by tacoring** [comment]
就顯示不出來 :(
![Uploading Screen Shot 2016-02-11 at 9.31.33 AM.png…]()

**Comment by kevin-doselection** [comment]
我用電腦模擬手機版，發現會被轉到https://localhost//Restricted%20Page%20Url?SID=sokv7v9odg250vq8voubl1da21

**Comment by tacoring** [comment]
我也是用點腦模擬手機版本. 會跑去這裡
https://www.ltsport.com/apptmng/Create
我從Contact或者dashboard進去都是這裡

你是從哪個點進去的. 

<img width="403" alt="screen shot 2016-02-11 at 11 58 41 am" src="https://cloud.githubusercontent.com/assets/730878/12988729/ef7f8588-d0b6-11e5-9f0d-b2f0643e33f7.png">

**Comment by kevin-doselection** [comment]
contact - appointment - apply now

**Comment by tacoring** [comment]
怪怪. 
我再研究研究

**Comment by tacoring** [comment]
我把檔案比對了一輪. 唯一的不同是layout裡的local.xml
我把apptmng這堆設定加進去, 還是沒有反應...:(

**Comment by kevin-doselection** [comment]
我明天幫你看一下

**Comment by kevin-doselection** [comment]
FYI 這是我看到的 https://youtu.be/oMxzxGSU4PM

**Comment by tacoring** [comment]
怪怪, 我用手機試跟你一樣的狀況. 

我用Chrome試, 卻是OK的. :(

繼續研究

**Comment by tacoring** [comment]
突然又可以了. 怪怪

你改好的嗎!?

**Comment by kevin-doselection** [comment]
我改了style.css page-title，不曉得有沒有關係

**Comment by kevin-doselection** [comment]
表單出來了，可是Make沒有用
Data不能關掉，會擋住下面的欄位

**Comment by tacoring** [comment]
year - make - model 改好

繼續處理date picker問題

**Comment by tacoring** [comment]
問一下, date你們有限制只有週二週三週四週五可以預約. 
那那個時間你們是在哪裡設定的!?

另外, 你們用的這個 jquery.simple-dtpicker.js 沒有支援mobile. 所以跳出來以後會無法消失. 
看要不要就是直接顯示, 而不是點了textfield才跑出來.

**Comment by kevin-doselection** [comment]
app/design/frontend/default/MAG050058/template/appt
datePick.phtml

直接顯示可以試試看

**Comment by tacoring** [comment]
我找到了一個設定, 點擊完關閉的選項. 
不過那個時間我找不到是哪裡去生出來的噎. 我暫時用hard code方式寫死.

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
我們用iphone進到appointment時，會轉到 localhost欸

**Comment by tacoring** [comment]
我用chrome是OK的. 
safari就會碰到一樣的問題
我查了一下, 可能是你們後台有些地方要處理一下
可以參考一下這篇
http://stackoverflow.com/questions/17639544/magento-is-automatically-redirecting-to-localhost-on-live-server

**Comment by kevin-doselection** [comment]
如果是瀏覽器的問題，你上面的方法沒有用
我想問題是在style.css，Javascript對每個瀏覽器的方法都要額外設定

**Comment by tacoring** [comment]
突然間可以了噎. 你有修改什麼嗎!?

我沒有特別在javascipt上設定什麼. 
service是自製的module, 有可能需要設定些什麼

**Comment by kevin-doselection** [comment]
沒有啊, safari還是一樣看不到
https://localhost//Restricted%20Page%20Url?SID=sokv7v9odg250vq8voubl1da21

**Comment by tacoring** [comment]
發現一個問題
如果已經先login 再去contact -> appointment -> apply now 就不會有問題
但是如果是沒login狀態
contact -> appointment -> apply now -> login <-----這時候就會出問題了

**Comment by kevin-doselection** [comment]
我想應該是URL link沒有pass過去，你檢查看是哪邊出問題
電腦不管有沒有登入都可以

**Comment by tacoring** [comment]
改成這樣咧, 之前是直接指到https://www.ltsport.com/apptmng/Create
我把它改成先指到https://www.ltsport.com/apptmng

**Comment by kevin-doselection** [comment]
行
