### ISSUE TITLE
cart 字的顏色 （白變黑）

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#10]

**Comment by tacoring** [comment]
有兩個Cart, 裡頭的白底的字都要改成黑的嗎!?

<img width="323" alt="screen shot 2016-02-09 at 11 35 44 am" src="https://cloud.githubusercontent.com/assets/730878/12928263/4d51f64c-cf21-11e5-966a-4e7b723749e0.png">
<img width="316" alt="screen shot 2016-02-09 at 11 35 50 am" src="https://cloud.githubusercontent.com/assets/730878/12928268/51ab9b26-cf21-11e5-9612-3308a8809bb8.png">

**Comment by kevin-doselection** [comment]
後者改就行了

**Comment by tacoring** [comment]
Done
