### ISSUE TITLE
用電腦看Menu的字不見了

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#12]
會是動到什麼嗎？

**Comment by tacoring** [comment]
手機版本還是?!

能否截個圖給我看一下

**Comment by kevin-doselection** [comment]
電腦版，這禮拜變這樣
會是什麼設定動到了嗎？

**Comment by tacoring** [comment]
是這個Menu!?

看起來還是ＯＫ的阿
<img width="992" alt="screen shot 2016-02-09 at 2 00 18 pm" src="https://cloud.githubusercontent.com/assets/730878/12932016/7c276b0a-cf35-11e5-86b3-905299466164.png">

**Comment by kevin-doselection** [comment]
對！
可是在某些人的電腦就看不到字，我的電腦是看得到

**Comment by tacoring** [comment]
這就妙了. 

我這包的CSS跟電腦版的CSS是分開的, 
而且我新增的都是另外加TAG上去. 也不可能會去覆蓋到原本的.

**Comment by kevin-doselection** [comment]
你有沒有上週的style.css?
我看看裡面

**Comment by tacoring** [comment]
我這沒有留哩. 
你用chrome去看看那台電腦顯示的css color

**Comment by tacoring** [comment]
你可以試著在   .main-menu加上color看看
或這針對裡頭每個項目加上color

<img width="902" alt="screen shot 2016-02-09 at 5 18 53 pm" src="https://cloud.githubusercontent.com/assets/730878/12936206/47dbcf78-cf51-11e5-8d20-43a4c28fbbc6.png">

**Comment by kevin-doselection** [comment]
Done

**Comment by tacoring** [comment]
搞定了?! 厲害

**Comment by kevin-doselection** [comment]
css在作怪
