### ISSUE TITLE
產品小圖不能點 會往上跳

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#15]

**Comment by tacoring** [comment]
這是解上次那個大圖不能scroll view造成的. 
原本的點擊效果是用elevateZoom做的, 但是因為那張圖的click被拿去用zoomIn用了. 所以不能scroll view. 

再研究看看怎麼解..

**Comment by tacoring** [comment]
搞定


解法:
http://stackoverflow.com/questions/26867626/image-of-elevatezoom-not-scrolling-in-cell-phone

**Comment by kevin-doselection** [comment]
行
