### ISSUE TITLE
shop by vehicle 字不見 （點選之後）

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#17]

**Comment by tacoring** [comment]
是說這個嗎!?


<img width="243" alt="screen shot 2016-02-16 at 8 29 49 pm" src="https://cloud.githubusercontent.com/assets/730878/13099891/0d375b3a-d4ec-11e5-8c6c-e60d63b864fb.png">

**Comment by kevin-doselection** [comment]
是的

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
做過第一次搜尋後，回上頁再看
Make Model會消失

**Comment by tacoring** [comment]
原本的設計就會這樣哩. 

<img width="1157" alt="screen shot 2016-02-18 at 1 30 34 pm" src="https://cloud.githubusercontent.com/assets/730878/13158890/e60e0654-d643-11e5-83f4-69d2d880d3b4.png">

**Comment by kevin-doselection** [comment]
可是我這裡不會誒
https://youtu.be/FDak8-iJNGY

**Comment by tacoring** [comment]
weird

**Comment by tacoring** [comment]
Ha, Safari不會出現這個問題. 

Chrome or phone 都有這個問題
https://www.youtube.com/watch?v=5p-a3tM6a6o&feature=youtu.be

不過試了下iphone, (Chrome)如果是按上面的上一頁就會不見那兩個options
但如果是用手滑動的上一頁就不會不見

iphone的safari兩種方式都不會不見

**Comment by kevin-doselection** [comment]
有辦法修嗎？雖然是小問題

**Comment by tacoring** [comment]
昨天找了一晚, 還沒啥頭緒. 
我再試試....

**Comment by tacoring** [comment]
本來想說去紀錄按下search時, options的狀態. 然後回上一頁時在讀取. 
不過javascript太不熟了....

搞不定 :(

**Comment by kevin-doselection** [comment]
好吧，你先看看appointment

**Comment by tacoring** [comment]
我用chrome是OK的. 
safari就會碰到一樣的問題
我查了一下, 可能是你們後台有些地方要處理一下
可以參考一下這篇
http://stackoverflow.com/questions/17639544/magento-is-automatically-redirecting-to-localhost-on-live-server

**Comment by kevin-doselection** [comment]
現在make model出不來

**Comment by tacoring** [comment]
我瞧瞧

**Comment by tacoring** [comment]
不知道為什麼出現一個錯誤訊息說. search必須要over https
所以我把year click那邊改成https就ok了
