### ISSUE TITLE
search btn大點

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#18]

**Comment by tacoring** [comment]
是這一個嗎!?
目前是128px * 17px, 想放到多大呢?!
<img width="244" alt="screen shot 2016-02-16 at 7 42 03 pm" src="https://cloud.githubusercontent.com/assets/730878/13099258/62c4bf2c-d4e5-11e5-92dc-52542e4a678e.png">

**Comment by kevin-doselection** [comment]
我想跟上面的dropdown box一樣的寬度會比較好看

**Comment by tacoring** [comment]
get it.

**Comment by tacoring** [comment]
Done
