### ISSUE TITLE
ltsport.com/checkout/onepage/success 原本有個PDF會在上面顯示

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#2]

**Comment by tacoring** [comment]
你說的應該是這個Image
https://www.ltsport.com/skin/frontend/default/MAG050058/images/orderd-confirm.jpg

是不是請設計師重新設計一份符合Mobile device大小的. 
然後我再放上去.

**Comment by kevin-doselection** [comment]
這個尺寸是以最小手機能放剛好的大小來設計嗎？

**Comment by tacoring** [comment]
可以請設計師設計一個版本, 然後放在你們覺得比較常用的手機上試試.

**Comment by kevin-doselection** [comment]
明天他來我跟他說

**Comment by kevin-doselection** [comment]
有辦法你放上去然後他按照手機寬度來縮放嗎？

**Comment by tacoring** [comment]
那是一張圖片哩...大螢幕的可能還看得清楚. 小螢幕就會小到一個不行啊. 

不然就是改成顯示文字. 只是會很長的一段而已.

**Comment by kevin-doselection** [comment]
2016-02-10 14:25 GMT-08:00 Kevin Yang <kevin.doselection@gmail.com>:

> 這個尺寸是以最小手機能放剛好的大小來設計嗎？
>
> On Feb 9, 2016, at 9:07 PM, Taco <notifications@github.com> wrote:
>
> 你說的應該是這個Image
>
> https://www.ltsport.com/skin/frontend/default/MAG050058/images/orderd-confirm.jpg
>
> 是不是請設計師重新設計一份符合Mobile device大小的.
> 然後我再放上去.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tacoring/ltsport/issues/2#issuecomment-182201194>.
>
>
>


-- 
Kevin Yang
IT Support Specialist, Do Selection Inc
Mobile: 626-272-0772
Address: 17005 Evergreen Pl, City of Industry CA 91745
Language: English, Chinese (Mandarin, Taiwanese)

**Comment by kevin-doselection** [comment]
![order confirm agree-web](https://cloud.githubusercontent.com/assets/17145866/13117402/a2e94694-d554-11e5-9628-36ecfc4ebbe3.jpg)

**Comment by tacoring** [comment]
Done..
