### ISSUE TITLE
checkout address 灰色看不到

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#20]

**Comment by tacoring** [comment]
是這邊的字嗎!? 能否截個圖
![Uploading Screen Shot 2016-02-16 at 8.09.22 PM.png…]()

**Comment by kevin-doselection** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17145866/13118029/30b4f084-d557-11e5-877e-264f1b28b78d.jpg)

**Comment by tacoring** [comment]
你標題是說checkout address !?

是說哪裏的address?

還是截圖中的paypal旁邊的白字. 

<img width="267" alt="screen shot 2016-02-21 at 10 21 53 pm" src="https://cloud.githubusercontent.com/assets/730878/13211019/bab14662-d8e9-11e5-9025-782b3132f8e2.png">

還是說
步驟一到六的標題灰字
<img width="252" alt="screen shot 2016-02-21 at 10 22 13 pm" src="https://cloud.githubusercontent.com/assets/730878/13211049/f7a4b9f0-d8e9-11e5-8ddd-08a54836daa7.png">

還是選擇check時跳出的住址
<img width="243" alt="screen shot 2016-02-21 at 10 25 53 pm" src="https://cloud.githubusercontent.com/assets/730878/13211080/347dfbb6-d8ea-11e5-82d1-aaa4ee121cac.png">

**Comment by kevin-doselection** [comment]
1. 能讓這三種付款方式都只佔一行？
![](https://cloud.githubusercontent.com/assets/730878/13211019/bab14662-d8e9-11e5-9025-782b3132f8e2.png)

2. 我手機看到的地址是灰色的...
![](https://cloud.githubusercontent.com/assets/730878/13211049/f7a4b9f0-d8e9-11e5-8ddd-08a54836daa7.png)

**Comment by tacoring** [comment]
1. 理論上可以, 不過就是花時間..
2. 了解. 我來試試

**Comment by tacoring** [comment]
手機上的顏色改成黑的. Done

**Comment by kevin-doselection** [comment]
Checked

**Comment by tacoring** [comment]
這樣OK嗎！？

**Comment by kevin-doselection** [comment]
可以
Payment Method能放在一行更好

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
Checkout Step 1: radio button 跟 text重疊

**Comment by tacoring** [comment]
Done

Step5, 我手機或者chrome上看都是一行哩 XD~
Chrome
<img width="281" alt="screen shot 2016-03-02 at 10 26 25 am" src="https://cloud.githubusercontent.com/assets/730878/13470514/604bd370-e061-11e5-9e97-bd9cb1616286.png">
Phone
![img_7869](https://cloud.githubusercontent.com/assets/730878/13470517/63abfc20-e061-11e5-8633-cdc98ef60de0.jpg)

**Comment by kevin-doselection** [comment]
你用iphone 5看，我手機是ASUS laser 5.5可能小一點
讓小手機看也不會跑掉比較好

Kevin Yang  
IT Support Specialist, Do Selection Inc
Mobile: 626-272-0772
Address: 17005 Evergreen Pl, City of Industry CA 91745
Language: English, Chinese (Mandarin, Taiwanese)

**Comment by tacoring** [comment]
哈～了解. 我來瞧瞧

**Comment by tacoring** [comment]
換成這樣 . ~

**Comment by kevin-doselection** [comment]
Nice
