### ISSUE TITLE
shopping cart during checkout cannot remove product

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#21]

**Comment by tacoring** [comment]
能否在描述一下狀況, 
那個empty cart的按鈕沒有作用, 我先拿掉了. 

目前我測試的是, 如果頁面在shopping cart裡頭, 然後從上頭的小車車裡去刪除一項產品, 只會把上頭的刪除. 整個頁面的shopping cart並不會不見. 必須重新整理後才會消失

**Comment by kevin-doselection** [comment]
我們是加到購物車去結帳，在checkout的過程如果想刪掉產品
會刪不掉

**Comment by tacoring** [comment]
了解
這是原本RWD這個的設計, 因為checkout前就有個確認畫面了. 如果這時候又要更改數量或者刪除可能意義不大. 
我是建議保持不動啦 ～
<img width="242" alt="screen shot 2016-02-19 at 10 17 51 pm" src="https://cloud.githubusercontent.com/assets/730878/13194925/c54185d6-d756-11e5-9a2c-563046cec86d.png">

**Comment by kevin-doselection** [comment]
我看到了...
那先維持原狀，我再想想
