### ISSUE TITLE
header call us

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#22]
能夠把call的功能放在header裡面嗎？ 小人頭像那欄

**Comment by tacoring** [comment]
應該沒辦法. 那一欄都是Dropdown button.
如果做在那個Menu裡頭應該就行

**Comment by kevin-doselection** [comment]
那放小人頭像底下，順序變成
My Account , My Order , Call Us先留這三個

**Comment by tacoring** [comment]
要不要放在Menu那裡. My account那邊是使用者的資訊, 放在這有點怪怪的.

**Comment by kevin-doselection** [comment]
可以
另外有辦法再按下去的時候跳出提示框嗎？

**Comment by tacoring** [comment]
跳出popup應該不行. 
我之前試了幾個作法, 都不行. 

把call us放在contact下面嗎. 順序是Home, Terms, contact, "Call Us" then products

**Comment by kevin-doselection** [comment]
順序：Home, Products, Contact Info, Call Us, Terms

**Comment by tacoring** [comment]
Done
<img width="258" alt="screen shot 2016-02-23 at 10 25 12 pm" src="https://cloud.githubusercontent.com/assets/730878/13277238/570b34b2-da7c-11e5-9091-a57868e39a61.png">
