### ISSUE TITLE
header - my cart (remove)

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#23]

**Comment by kevin-doselection** [comment]
跟最右邊的購物車重複

**Comment by tacoring** [comment]
所以是要移掉!? 那個!?

能否截個圖一下.

**Comment by kevin-doselection** [comment]
[Document1.docx](https://github.com/tacoring/ltsport/files/134792/Document1.docx)

**Comment by tacoring** [comment]
這個我會建議留著, 因為
- my cart是跳進去看所有要購買的明細包含價錢的detail. 
- Checkout 則是使用者都決定好了想直接checkout就可以從這進入, 而不用多按兩次按鈕進到checkout. 

而header上的cart只是讓使用者大概看一下現在有什麼, 看完就繼續購物. 

我是建議留著啦, 如果要拿掉我就研究一下怎麼拿掉

**Comment by kevin-doselection** [comment]
能夠直接改數量最好
如果不行，就拿掉

**Comment by tacoring** [comment]
可以改數量低
![Uploading Screen Shot 2016-02-22 at 11.00.27 AM.png…]()
