### ISSUE TITLE
remove "my order" in detail

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#24]
my order - detail 裡面最上面的my account  最下面的my order移除

原本order裡面有message可以傳，不見了

**Comment by tacoring** [comment]
I try,  message那個我瞧瞧

**Comment by tacoring** [comment]
My Account 裡面最上面的my account 最下面的my order也要移除嗎!?

**Comment by kevin-doselection** [comment]
不用移除
不過有辦法把在Header底下那個My Account 藏起來嗎？

**Comment by tacoring** [comment]
是說這個My account嗎!? 這個藏起來使用者就沒有捷徑去dashboard了哩...

<img width="259" alt="screen shot 2016-02-22 at 11 01 32 am" src="https://cloud.githubusercontent.com/assets/730878/13229017/a99f2b72-d953-11e5-98ce-a818c51fd2fc.png">

**Comment by kevin-doselection** [comment]
是這個
![screen shot 2016-02-22 at 11 15 51 am](https://cloud.githubusercontent.com/assets/17145866/13229411/af57a862-d955-11e5-822e-b1206b6aebf3.png)

**Comment by tacoring** [comment]
所以這個My account跟最下面的my order都要拿掉. 對吧
<img width="264" alt="screen shot 2016-02-22 at 10 30 22 pm" src="https://cloud.githubusercontent.com/assets/730878/13243489/040f0e96-d9b4-11e5-8c69-1f9a7ac2c581.png">

**Comment by kevin-doselection** [comment]
沒錯

**Comment by tacoring** [comment]
Done
