### ISSUE TITLE
product - spilt two button

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#28]
像其他menu一樣
這樣product search result page不用再顯示了

![shop by product-after](https://cloud.githubusercontent.com/assets/17145866/13095110/30227940-d4c4-11e5-9c0f-57c7a27733a6.png)
![shop by product-before](https://cloud.githubusercontent.com/assets/17145866/13095112/3024b02a-d4c4-11e5-8ebd-a711245953a8.png)
![shop by vehicle-after](https://cloud.githubusercontent.com/assets/17145866/13095109/3021b17c-d4c4-11e5-9d2a-55e1f804ccfd.png)
![shop by vehicle](https://cloud.githubusercontent.com/assets/17145866/13095111/302403dc-d4c4-11e5-8563-5c8148b4620b.png)

**Comment by tacoring** [comment]
來試試

**Comment by tacoring** [comment]
https://www.ltsport.com/mobile_shopbyproduct
Shop By Product沒啥問題

Shop By Vehicle就要花點時間, 
https://www.ltsport.com/mobile_shopbyvehicle

因為CMS不給寫javascript. 通通會被block掉.. 所以要研究一下

**Comment by tacoring** [comment]
Shop By Vehicle那個
我找了很多方法再CMS中寫Javascript. 不過都不成功. ...
https://www.ltsport.com/mobile_shopbyvehicle

你有沒有什麼idea

**Comment by kevin-doselection** [comment]
你可以用Contact那樣的方法做，然後隱藏Shop by Product(Vehicle)嗎？

**Comment by tacoring** [comment]
不太懂?!
你是說像contact menu
https://www.ltsport.com/mobile_c_m
中把沒選到的button隱藏起來嗎!?  

CMS中還可以偷偷跑CSS, 但是Javascript就完全不行..

**Comment by kevin-doselection** [comment]
如果說改成下面這樣你覺得有辦法嗎？
點選Product -> 新頁面只有 Shop by Vehicle & Shop by Category
Shop by Vehicle: 原理是用URL做搜尋，你讀得到User的input，就可以寫在自己的code裡
Shop by Category: 這個可以直接連到原本的Category頁面，你再把Mobile version page's Javascript disable(remove).

**Comment by tacoring** [comment]
我大概了解你的意思, 我試著用那個service的做法. 
在local.xml裡頭多加一個page, 有可能可以做得到 XD~

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
Nice
換個做法比較簡單吧 :)

**Comment by kevin-doselection** [comment]
shop by category的圖可以放大到邊界嗎？

**Comment by tacoring** [comment]
你是說把它拉成橫的!?

**Comment by kevin-doselection** [comment]
一樣的版面，但旁邊不要留白

**Comment by tacoring** [comment]
你是說把這個拉到最大！？

<img width="274" alt="screen shot 2016-03-09 at 10 17 01 pm" src="https://cloud.githubusercontent.com/assets/730878/13661106/afa43366-e644-11e5-9424-2f00238088b8.png">

**Comment by kevin-doselection** [comment]
恩啊左右兩邊不要有空間

**Comment by tacoring** [comment]
很難做到responsive,
裡頭有ul li 
頂多以你們覺得最小的螢幕把它塞滿...

**Comment by kevin-doselection** [comment]
那用iphone6s放吧 老闆手機是這隻

**Comment by tacoring** [comment]
那在iphone4上看版面可能會亂掉喔.

**Comment by kevin-doselection** [comment]
不是放大而是跑掉哦...
有什麼辦法可以避免？

**Comment by tacoring** [comment]
我可以先試試看～

**Comment by kevin-doselection** [comment]
iphone6 s

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
Android good
iPhone 跑出去版面了

**Comment by tacoring** [comment]
iphone 6嗎！？

**Comment by kevin-doselection** [comment]
恩 我手機沒問題
老闆看的有問題

**Comment by tacoring** [comment]
能否拍個照瞧瞧是啥問題.

**Comment by kevin-doselection** [comment]
![qq](https://cloud.githubusercontent.com/assets/17145866/13711792/4affdb18-e775-11e5-8cdf-1e44b713f482.png)

**Comment by tacoring** [comment]
怪怪, 確定是iphone6

**Comment by tacoring** [comment]
Try Try see. Done
