### ISSUE TITLE
change background

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#29]
![background](https://cloud.githubusercontent.com/assets/17145866/13095129/45d54b50-d4c4-11e5-96f1-ac497d588fd7.jpg)

**Comment by tacoring** [comment]
OK~

**Comment by tacoring** [comment]
Done

**Comment by kevin-doselection** [comment]
左邊能夠靠著邊界嗎？好像還差一點

**Comment by tacoring** [comment]
能否給我大張點的background. 
不然我把左邊貼在邊界上. 右邊就會冒出來. XD
<img width="316" alt="screen shot 2016-02-17 at 10 16 29 am" src="https://cloud.githubusercontent.com/assets/730878/13119756/976a41a0-d55f-11e5-914e-697ce4e8ee17.png">

**Comment by kevin-doselection** [comment]
![background0217](https://cloud.githubusercontent.com/assets/17145866/13120303/12f857e2-d562-11e5-8fe1-c411e30bc8c3.png)

**Comment by tacoring** [comment]
Done.

**Comment by kevin-doselection** [comment]
你用模擬器跑iphone 6plus試試看...
寬度ＯＫ，但是變成長度不夠

**Comment by tacoring** [comment]
How about now?!

**Comment by kevin-doselection** [comment]
good
