### ISSUE TITLE
Live Chat我手機看不見耶 (ASUS Laser Zenfone)

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#3]

**Comment by tacoring** [comment]
試試看
我加了Zenfonel到System->Design

**Comment by kevin-doselection** [comment]
還是不行

**Comment by tacoring** [comment]
:(

**Comment by tacoring** [comment]
幫我用你的zenfone開這個網頁一下
http://detectmobilebrowsers.com/
應該會有一行user agent跑出來. 

幫我copy下來

**Comment by kevin-doselection** [comment]
Mozilla/5.0 (Linux; Android 5.0.2; ASUS_Z00TD Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.95 Mobile Safari/537.36

Kevin Yang  

IT Support Specialist, Do Selection Inc

Mobile: 626-272-0772

Address: 17005 Evergreen Pl, City of Industry CA 91745

Language: English, Chinese (Mandarin, Taiwanese)

-------- Original Message --------

**Comment by tacoring** [comment]
try try see.

**Comment by kevin-doselection** [comment]
還是看不到..

**Comment by tacoring** [comment]
try  try see

**Comment by kevin-doselection** [comment]
不行

**Comment by tacoring** [comment]
我再找找方法..... :(

**Comment by kevin-doselection** [comment]
沒事 這個問題先放著
