### ISSUE TITLE
Product URL在Mobile version無效

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#30]
像這個
https://www.ltsport.com/cb-su-4d-202.html
你知道為什麼嗎？

**Comment by tacoring** [comment]
看起來可以哩
<img width="425" alt="screen shot 2016-02-24 at 10 20 31 am" src="https://cloud.githubusercontent.com/assets/730878/13295990/439bb302-dae0-11e5-8436-60bc03368ab2.png">

**Comment by kevin-doselection** [comment]
是為什麼？
