### ISSUE TITLE
URL not working in mobile device

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#31]
這些產品電腦看得到，但在手機上都會回到首頁
Item ID	Issue title
FM-UNVS-AR1,FM-UNVS-AR4-301-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-302-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-303-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-305-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-306-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-308-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-310-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR1,FM-UNVS-AR4-312-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-302-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-303-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-304-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-305-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-306-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-307-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-308-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-309-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-310-WS	Product pages cannot be accessed from a mobile device
FM-UNVS-AR3,FM-UNVS-AR4-311-WS	Product pages cannot be accessed from a mobile device

**Comment by tacoring** [comment]
我試了幾個, 都可以噎. 

不過你們的網站有時真的怪怪的, 一些操作都會跳回首頁. 
<img width="554" alt="screen shot 2016-03-03 at 8 37 41 pm" src="https://cloud.githubusercontent.com/assets/730878/13518165/ec4b133a-e17f-11e5-8d5d-337083d05964.png">

<img width="511" alt="screen shot 2016-03-03 at 8 38 28 pm" src="https://cloud.githubusercontent.com/assets/730878/13518166/f1825278-e17f-11e5-84b8-ed65a395a9d0.png">
