### ISSUE TITLE
Product title 大寫

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#32]
為什麼我把title都改成小寫之後，網站跟著變，手機卻沒有
你有寫強制大寫嗎？

**Comment by tacoring** [comment]
應該是CSS 強制把它大寫了, 
text-transform: uppercase;

需要我把它拿掉嗎!? 
<img width="243" alt="screen shot 2016-03-04 at 10 25 46 am" src="https://cloud.githubusercontent.com/assets/730878/13536218/7c924670-e1f3-11e5-8f3e-e004b3b9dafb.png">

**Comment by kevin-doselection** [comment]
用註解把它disable

**Comment by kevin-doselection** [comment]
我清掉cache還是一樣，你那邊看起來是什麼

**Comment by tacoring** [comment]
我還沒動啦～正在

**Comment by tacoring** [comment]
list 跟 product view都改好了
![Uploading Screen Shot 2016-03-04 at 10.57.42 AM.png…]()
<img width="269" alt="screen shot 2016-03-04 at 10 57 35 am" src="https://cloud.githubusercontent.com/assets/730878/13537063/f1ee57b6-e1f7-11e5-92ed-fe804749bb8a.png">

**Comment by kevin-doselection** [comment]
thx
