### ISSUE TITLE
new account

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#33]
/customer/account/create
版面可以往右滑，是太大嗎？

**Comment by tacoring** [comment]
這張圖太大...

<img width="436" alt="screen shot 2016-03-09 at 9 59 13 pm" src="https://cloud.githubusercontent.com/assets/730878/13660805/37af4668-e642-11e5-90ad-55099495aebb.png">

**Comment by kevin-doselection** [comment]
那我直接換成小圖，就會變正常嗎？

**Comment by tacoring** [comment]
YES
這張圖的大小是454(w) × 149(height)

iphone 4的寬是320 整個超出很多

**Comment by kevin-doselection** [comment]
明天我換小圖看看，不過在你手機上看ＯＫ嗎？

**Comment by tacoring** [comment]
我在chrome上用hard code就可以.

**Comment by kevin-doselection** [comment]
你先hard code設定寬度，設計師不在我拿不到小的圖樣

**Comment by tacoring** [comment]
這個我找了老半天, 原來你們有個plugin --> clarion把所有user的register都導倒
frontend/base/default/template/clarion/customerattribute/form/register.phtml去了
所以我如果改了這個連你們的都會動到. 

或是我用CSS把圖片的寬度拉到最大375px(iphone6s)的大小

**Comment by kevin-doselection** [comment]
Android good
iPhone 也是跑出版面....

**Comment by tacoring** [comment]
iphone是哪一隻！？
因為我拉成375px. 那是符合iphone 6的

不然我拉最小的iphone 4.. 320px

**Comment by kevin-doselection** [comment]
new account, appointment都有一樣的現象

**Comment by tacoring** [comment]
Appointment是下面remark太寬. 這應該可以改成適應螢幕的寬

new account那個能否結個圖給我瞧瞧. 不然用說的我真的很難去想像

**Comment by kevin-doselection** [comment]
appointment OK
New account OK
