### ISSUE TITLE
my order - message

### ISSUE THREAD

**Issue by kevin-doselection** [tacoring/ltsport#35]
my order的leave a message沒有功能欸

**Comment by tacoring** [comment]
這個是從哪進去的呀!?

**Comment by kevin-doselection** [comment]
手機登入帳號之後，有很多紅色按鈕對吧
往下找一個leave a message about my order
裡面沒有message的功能

**Comment by tacoring** [comment]
Got it .

**Comment by tacoring** [comment]
你知道你們message這段code放在哪裡嗎!?

**Comment by kevin-doselection** [comment]
html/app/design/frontend/default/MAG050058/template/ordertickets/chat.html

**Comment by tacoring** [comment]
這隻我知道, 不過你知道那個畫面在哪call這隻的.

**Comment by kevin-doselection** [comment]
https://www.ltsport.com/sales/order/history/

**Comment by tacoring** [comment]
隨手記錄一下, history的畫面是在  template/ordermonitor/history.phtml

**Comment by tacoring** [comment]
Done
