### ISSUE TITLE
Compare products可以拿掉

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#4]

**Comment by kevin-doselection** [comment]
http://www.templatemonster.com/help/magento-how-to-disable-compare-products-feature.html#gref

**Comment by tacoring** [comment]
這我有試過, 我之前就把product view裏頭的add to 還有compare移掉了
現在是在product search後顯示的product list還是會有compare跟recently viewed

**Comment by tacoring** [comment]
Done, 只留下recently viewed
