### ISSUE TITLE
Menu + terms + contact - others

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#6]

**Comment by tacoring** [comment]
1. 順序是Home, Terms, Contact

2. Order 我建議是直接到後台的Catalog把others "Is Active" disable掉
<img width="649" alt="screen shot 2016-02-09 at 11 25 29 am" src="https://cloud.githubusercontent.com/assets/730878/12928028/278db71c-cf20-11e5-906e-af1e9eb1bf93.png">

**Comment by kevin-doselection** [comment]
沒問題，你直接關

**Comment by tacoring** [comment]
Done
