### ISSUE TITLE
product detail title 小一點 ; 產品小圖再小一點

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#7]

**Comment by tacoring** [comment]
How small you want ?!

**Comment by kevin-doselection** [comment]
現在的font是多大？
小圖在iphone6會變成三個在第一行 一個在第二行

**Comment by tacoring** [comment]
1. 用h1 tag 20px
2. thumb是75px * 75px

**Comment by kevin-doselection** [comment]
1. h1 14 px
2. 60 px * 60 px

**Comment by tacoring** [comment]
#5 padding移掉後, 空出很多空間. 
這樣是不是就OK了

<img width="323" alt="screen shot 2016-02-09 at 11 32 53 am" src="https://cloud.githubusercontent.com/assets/730878/12928188/e2efe0b6-cf20-11e5-94d3-5dcf5bc090f9.png">

**Comment by kevin-doselection** [comment]
行
