### ISSUE TITLE
dropdown 字的顏色不明顯 (category, onepage/checkout

### ISSUE THREAD

**Issue by tacoring** [tacoring/ltsport#8]

**Comment by tacoring** [comment]
是指產品頁的description!?

**Comment by kevin-doselection** [comment]
不是
用手機看的話，所有的下拉式選單的字都是灰的

**Comment by tacoring** [comment]
能否截個圖給我看一下. 我在iphone 6上是正常的

![img_7457](https://cloud.githubusercontent.com/assets/730878/12930393/e46bfa9a-cf2c-11e5-9fd8-84c5f101562e.jpg)

**Comment by kevin-doselection** [comment]
Kevin Yang  

IT Support Specialist, Do Selection Inc

Mobile: 626-272-0772

Address: 17005 Evergreen Pl, City of Industry CA 91745

Language: English, Chinese (Mandarin, Taiwanese)

-------- Original Message --------

**Comment by kevin-doselection** [comment]
![screenshot_2016-02-09-13-59-26](https://cloud.githubusercontent.com/assets/17145866/12933845/45768d84-cf3f-11e5-9fca-0f74664be5bd.jpg)

**Comment by tacoring** [comment]
Done.
